name: Commit Subject Check

on: [push, pull_request]

jobs:
  commit-subject-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to check sequence and duplicates

      - name: Validate commit subjects
        run: |
          regex="^(GDSYNKT|GDSYNKL|GDSYNKK|GDSYNKH)-[0-9]+: "
          for commit in $(git log --format="%s" --no-merges -n 10); do
            if ! [[ $commit =~ $regex ]]; then
              echo "❌ Commit message '$commit' does not follow the required format!"
              exit 1
            fi
          done
          echo "✅ All commit messages follow the correct format!"