name: Commit Subject Check

on: [push, pull_request]

jobs:
  commit-subject-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to check sequence and duplicates

      - name: Validate commit subjects
        run: |
          # Define the required pattern
          PATTERN="^(GDSYNKT|GDSYNKL|GDSYNKK|GDSYNKH)-([0-9]+): .+$"

          # Get all new commit subjects (first line only)
          commits=$(git log --format=%s --no-merges origin/main..HEAD)

          # Fetch all past commit subjects
          all_commit_subjects=$(git log --format=%s)

          # Track the highest existing number per prefix
          declare -A latest_commit_number

          # Find the latest commit number per prefix
          while IFS= read -r subject; do
            if [[ $subject =~ $PATTERN ]]; then
              prefix="${BASH_REMATCH[1]}"
              number="${BASH_REMATCH[2]}"
              
              if [[ -z ${latest_commit_number[$prefix]} || ${number} -gt ${latest_commit_number[$prefix]} ]]; then
                latest_commit_number[$prefix]=$number
              fi
            fi
          done <<< "$all_commit_subjects"

          # Validate new commit subjects
          while IFS= read -r subject; do
            if [[ $subject =~ $PATTERN ]]; then
              prefix="${BASH_REMATCH[1]}"
              number="${BASH_REMATCH[2]}"
              expected_number=$((latest_commit_number[$prefix] + 1))

              # Ensure numbers increase sequentially
              if [[ -n ${latest_commit_number[$prefix]} && $number -ne $expected_number ]]; then
                echo "❌ Invalid commit: '$subject'."
                echo "🚨 Expected '${prefix}-$expected_number: <subject>' but got '${subject}'."
                exit 1
              fi

              # Ensure no duplicate subjects
              if echo "$all_commit_subjects" | grep -Fxq "$subject"; then
                echo "❌ Duplicate commit subject found: '$subject'"
                exit 1
              fi
            else
              echo "❌ Invalid commit subject format: '$subject'."
              echo "✅ Expected format: 'GDSYNKT-123: Subject' (or GDSYNKL/GDSYNKK/GDSYNKH)"
              exit 1
            fi
          done <<< "$commits"